"""initial migration

Revision ID: 10155bac947a
Revises: 
Create Date: 2025-11-18 22:37:25.781956

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '10155bac947a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('period_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_teacher_id', sa.Integer(), nullable=True))
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'teachers', ['assigned_teacher_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('size')

    with op.batch_alter_table('education_levels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level_type', sa.Enum('nursery', 'lower_primary', 'upper_primary', 'secondary', name='level_types'), nullable=False))
        batch_op.drop_column('description')

    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.drop_column('room_type')

    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.drop_column('timezone')

    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.alter_column('code',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=10),
               nullable=False)
        batch_op.alter_column('subject_type',
               existing_type=mysql.ENUM('theory', 'lab', 'practical'),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('subjects_ibfk_2'), type_='foreignkey')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('education_level_id')
        batch_op.drop_column('periods_per_week')

    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qualification', sa.Enum('Nursery', 'Lower primary', 'Upper primary', 'Secondary', name='teacher_qualification'), nullable=False))
        batch_op.alter_column('first_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('last_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('teachers_ibfk_1'), type_='foreignkey')
        batch_op.drop_column('education_level_id')
        batch_op.drop_column('notes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('education_level_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('teachers_ibfk_1'), 'education_levels', ['education_level_id'], ['id'], ondelete='SET NULL')
        batch_op.alter_column('last_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('first_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('qualification')

    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('periods_per_week', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('education_level_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True))
        batch_op.create_foreign_key(batch_op.f('subjects_ibfk_2'), 'education_levels', ['education_level_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('subject_type',
               existing_type=mysql.ENUM('theory', 'lab', 'practical'),
               nullable=True)
        batch_op.alter_column('code',
               existing_type=sa.String(length=10),
               type_=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=150),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)

    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timezone', mysql.VARCHAR(length=64), nullable=True))

    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('room_type', mysql.ENUM('classroom', 'lab', 'hall'), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)

    with op.batch_alter_table('education_levels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', mysql.TEXT(), nullable=True))
        batch_op.drop_column('level_type')

    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('size', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('name',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('assigned_teacher_id')

    op.drop_table('period_template')
    # ### end Alembic commands ###
